global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeaat_interval: 1h
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: diemhieu2310@gmail.com
    from: diemhieu2310@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: diemhieu2310@gmail.com
    auth_identity: diemhieu2310@gmail.com
    auth_password: 26092310
    send_resolved: true
    
    
