version: '3.6'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - alertmanager:alertmanager
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./rules.yml:/etc/prometheus/rules.yml:ro
    - ./alertmanager.yml:/etc/prometheus/alertmanager.yml:ro
    depends_on:
    - node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
    - 9100  
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    depends_on:
    - alertmanager
  alertmanager: 
    image: "prom/alertmanager"
    ports:
    - "9093:9093"
    expose:
    - "9093" 
    volumes:
    - "/tmp/prom:/tmp/prom"
    - "$PWD/alertmanager.yml:/alertmanager/alertmanager.yml" 
    - ./rules.yml:/etc/prometheus/rules.yml:ro
    depends_on:
    - grafana 
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    
   
        
